name: Leo District MD112a
favicon: null
layout_spectrum: 0.23933
typography_spectrum: 0.72333
title: Leo District MD112a
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.625
  lightness: 0.4375
  saturation: 0.625
  rhythmicContrast: 0.5
purpose: []
